export interface BrightStar {
  id: string
  name: string
  raHours: number
  decDeg: number
  magnitude: number
  colorIndex?: number
}

// Generated by scripts/generate-bright-stars.mjs.
// Source: fallback seed list
// Magnitude limit: 6.5
export const BRIGHT_STARS: BrightStar[] = [
  { id: "sirius", name: "Sirius", raHours: 6.7525, decDeg: -16.7161, magnitude: -1.46, colorIndex: 0 },
  { id: "canopus", name: "Canopus", raHours: 6.3992, decDeg: -52.6957, magnitude: -0.74, colorIndex: 0.15 },
  { id: "rigil-kentaurus", name: "Rigil Kentaurus", raHours: 14.6601, decDeg: -60.8356, magnitude: -0.27, colorIndex: 0.71 },
  { id: "arcturus", name: "Arcturus", raHours: 14.261, decDeg: 19.1825, magnitude: -0.05, colorIndex: 1.23 },
  { id: "vega", name: "Vega", raHours: 18.6156, decDeg: 38.7837, magnitude: 0.03, colorIndex: 0 },
  { id: "capella", name: "Capella", raHours: 5.2782, decDeg: 45.998, magnitude: 0.08, colorIndex: 0.8 },
  { id: "rigel", name: "Rigel", raHours: 5.2423, decDeg: -8.2016, magnitude: 0.13, colorIndex: -0.03 },
  { id: "procyon", name: "Procyon", raHours: 7.655, decDeg: 5.225, magnitude: 0.34, colorIndex: 0.42 },
  { id: "achernar", name: "Achernar", raHours: 1.6286, decDeg: -57.2368, magnitude: 0.46, colorIndex: -0.16 },
  { id: "betelgeuse", name: "Betelgeuse", raHours: 5.9195, decDeg: 7.4071, magnitude: 0.5, colorIndex: 1.85 },
  { id: "hadar", name: "Hadar", raHours: 14.0637, decDeg: -60.373, magnitude: 0.61, colorIndex: -0.23 },
  { id: "altair", name: "Altair", raHours: 19.8464, decDeg: 8.8683, magnitude: 0.76, colorIndex: 0.22 },
  { id: "acrux", name: "Acrux", raHours: 12.4433, decDeg: -63.0991, magnitude: 0.76, colorIndex: -0.24 },
  { id: "aldebaran", name: "Aldebaran", raHours: 4.5987, decDeg: 16.5093, magnitude: 0.85, colorIndex: 1.54 },
  { id: "spica", name: "Spica", raHours: 13.4199, decDeg: -11.1613, magnitude: 0.98, colorIndex: -0.23 },
  { id: "antares", name: "Antares", raHours: 16.4901, decDeg: -26.432, magnitude: 1.06, colorIndex: 1.83 },
  { id: "pollux", name: "Pollux", raHours: 7.7553, decDeg: 28.0262, magnitude: 1.14, colorIndex: 1 },
  { id: "fomalhaut", name: "Fomalhaut", raHours: 22.9608, decDeg: -29.6222, magnitude: 1.16, colorIndex: 0.09 },
  { id: "deneb", name: "Deneb", raHours: 20.6905, decDeg: 45.2803, magnitude: 1.25, colorIndex: 0.09 },
  { id: "regulus", name: "Regulus", raHours: 10.1395, decDeg: 11.9672, magnitude: 1.35, colorIndex: -0.11 },
  { id: "adhara", name: "Adhara", raHours: 6.9771, decDeg: -28.9721, magnitude: 1.5, colorIndex: -0.21 },
  { id: "castor", name: "Castor", raHours: 7.5767, decDeg: 31.8883, magnitude: 1.58, colorIndex: 0.03 },
  { id: "gacrux", name: "Gacrux", raHours: 12.5194, decDeg: -57.1132, magnitude: 1.63, colorIndex: 1.59 },
  { id: "bellatrix", name: "Bellatrix", raHours: 5.4189, decDeg: 6.3497, magnitude: 1.64, colorIndex: -0.22 },
  { id: "elnath", name: "Elnath", raHours: 5.4382, decDeg: 28.6075, magnitude: 1.65, colorIndex: -0.13 },
  { id: "miaplacidus", name: "Miaplacidus", raHours: 9.22, decDeg: -69.7172, magnitude: 1.67, colorIndex: 0.02 },
  { id: "alnilam", name: "Alnilam", raHours: 5.6036, decDeg: -1.2019, magnitude: 1.69, colorIndex: -0.18 },
  { id: "alnair", name: "Alnair", raHours: 22.1372, decDeg: -46.9609, magnitude: 1.73, colorIndex: -0.07 },
  { id: "alioth", name: "Alioth", raHours: 12.9005, decDeg: 55.9598, magnitude: 1.76, colorIndex: -0.02 },
  { id: "dubhe", name: "Dubhe", raHours: 11.0621, decDeg: 61.751, magnitude: 1.79, colorIndex: 1.06 },
  { id: "mirfak", name: "Mirfak", raHours: 3.4054, decDeg: 49.8612, magnitude: 1.79, colorIndex: 0.48 },
  { id: "kaus-australis", name: "Kaus Australis", raHours: 18.4029, decDeg: -34.3846, magnitude: 1.85, colorIndex: -0.03 },
  { id: "alkaid", name: "Alkaid", raHours: 13.7923, decDeg: 49.3133, magnitude: 1.85, colorIndex: -0.19 },
  { id: "avior", name: "Avior", raHours: 8.3752, decDeg: -59.5095, magnitude: 1.86, colorIndex: 1.2 },
  { id: "sargas", name: "Sargas", raHours: 17.6219, decDeg: -42.9978, magnitude: 1.86, colorIndex: 0.41 },
  { id: "menkalinan", name: "Menkalinan", raHours: 5.9921, decDeg: 44.9474, magnitude: 1.9, colorIndex: 0 },
]
